# Generated by Django 3.1.4 on 2020-12-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0002_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='condidate',
        ),
    ]
