# Generated by Django 3.1.4 on 2020-12-08 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0004_remove_add_candidates_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='con',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='voteapp.add_candidates'),
            preserve_default=False,
        ),
    ]
